# Generated by Django 5.0.7 on 2024-07-12 18:44

import django.db.models.deletion
import ipay.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_name', models.CharField(max_length=25, verbose_name='VLAN İsmi')),
                ('vlan_value', models.PositiveIntegerField(verbose_name='VLAN Numarası')),
                ('start_ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='Başlangıç IP Adresi')),
                ('end_ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='Bitiş IP Adresi')),
                ('netmask', models.GenericIPAddressField(protocol='IPv4', verbose_name='Netmask')),
                ('description', models.TextField(max_length=150, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'VLAN',
                'verbose_name_plural': "VLAN'lar",
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True, verbose_name='MAC Adresi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True, verbose_name='IP Adresi')),
                ('description', models.TextField(max_length=150, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiflik Durumu')),
                ('wireless', models.BooleanField(default=False, verbose_name='Kablosuz')),
                ('created_by', models.ForeignKey(blank=True, on_delete=models.SET(ipay.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden Kullanıcı')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipay.vlan', verbose_name='VLAN')),
            ],
            options={
                'verbose_name': 'Cihaz',
                'verbose_name_plural': 'KAYITLI CİHAZLAR',
            },
        ),
    ]
